### ISSUE TITLE
[账户安全] 使用加盐SHA512来保护明文账号

### ISSUE THREAD

**Issue by Acpear** [NonLoop/NonLoop#2]
鉴于 Bot 账户的身份特殊性以及腾讯™打击力度，手法的不可预见性，直接公开暴露账号（甚至主人账号）是危险的。明文公开账号也可能诱发恶意人士对友好 Bot 的滥用或举报。因此不建议公开 Bot 的明文账号，并取消主人账号列的显示。

哈希算法具有单向性，能够较好地解决上述的账户安全性问题。比如使用`账号+对应生日`的组合方式，通过以下步骤得出哈希值，并将哈希值存储于本仓库中，将部分程度地增加账户的安全性。

> 我的 QQ™ Bot 的账户为 A (eg: 1112223344)
> 我的 QQ™ Bot 的账户的生日为 B (eg: 20220805)
> origin_text = A + "&"  + B
> hash_text = Sha512(origin_text)
> hash_text 即为上述“哈希值”，上传至本仓库即可

该方式极大程度避免了腾讯™ 从此仓库获取 Bot 账号并采取处理方式的可能性，因为腾讯面临的潜在 Bot 用户数量是巨大的，而Sha512计算则需要消耗大量资源。但对于开发者而言，亦增加了任务：

1. 当自己的 Bot 的生日变动时，及时将最新hash值上传至本仓库。
2. 建立“不是人，是 Bot”数据库（shujuku.txt），储存 Bot 密接范围内的其他 Bot 账号，并做出相应判断（如：防止复读风暴），使之统一为“人”服务。

Q：选取“生日”作为`origin_text`的一员，是否有特殊性？
A：具有特殊性，生日一般不会变动，可以拿过来作为识别特征来用，同时生日具有可变性，对自己的 Bot 改个生日就更改了hash判据，更有利于摆脱腾讯™ 对本仓库的利用。

**Comment by djkcyl** [comment]
介于你提出的方案，我有几个疑点
1. 协议库无法方便的拿到生日，也就无法在 sdk 进行 hash 判断
2. 腾讯早就掌握了所有的 bot，不差咱库里这点
3. 你的协议端已经很明显的告诉了腾讯：“我是机器人”

针对以上问题，给出一个解决方案：
> 在收到 issue 后用 bot 使用 rsa 对 qq 号二次加密后删除 issue 并使用密文重发，随后人工审核后 bot 入库

**但这终究是个防君子不防小人的做法**

**Comment by Acpear** [comment]
啊，那……（啊吧啊吧）反正就是……能更安全一下……就好
